
{% set data = load_setup_py_data() %}

package:
  name: pandas-visual-analysis
  version: {{ data['version'] }}

source:
  path: ..

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools >=49.2.0

  run:
    - python
    - setuptools >=49.2.0
    - traitlets >=4.3.3
    - pandas >=1.1.0
    - ipywidgets >=7.5.1
    - numpy >=1.19.1
    - plotly >=4.9.0


about:
  home: {{ data['url'] }}
  license: {{ data['license'] }}
summary: {{ data['description'] }}